name: Nightly Build

on:
    schedule:
        - cron:
            '0 5 * * *'
    workflow_dispatch:

jobs:
  ci:
  
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            host: windows
            arch: x86_64
            cargo-target: x86_64-pc-windows-msvc

          - name: Linux x86_64
            host: linux
            arch: x86_64
            cargo-target: x86_64-unknown-linux-gnu

          - name: macOS x86_64
            host: macos
            arch: x86_64
            cargo-target: x86_64-apple-darwin

          - name: macOS aarch64
            host: macos
            arch: aarch64
            cargo-target: aarch64-apple-darwin

    name: Nightly - ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
          components: clippy
          targets: ${{ matrix.cargo-target }}

    - name: Build
      run: |
        cargo build \
        --all-features \
        --release \
        --target ${{ matrix.cargo-target }}
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ steps.date.outputs.date }}
        release_name: Nightly Build ${{ steps.date.outputs.date }}
        body: Nightly build artifacts.

    - name: Give Permissions
      if: matrix.host != 'windows' # Only on non-Windows
      run: chmod +x ./target/${{ matrix.cargo-target }}/release/rere
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/${{ matrix.cargo-target }}/release/rere.exe # Direct path to the executable
        asset_name: your-project-name-${{ matrix.host }}.exe # Name of the executable
        asset_content_type: application/octet-stream # Important for executables